#!/bin/zsh

RESOLUTION=800x600
ID=1  # $DISPLAY NUMBER
WM=i3 # WINDOW MANAGER
OYSTER=zsh # Can i use $SHELL?
XEPHYR_START="
	Xephyr -br -ac -noreset -screen $RESOLUTION :$ID &
	sleep 2
	DISPLAY=:$ID $WM
"

# nix-user-chroot source
NUC_SRC="https://github.com/nix-community/nix-user-chroot/releases/download/1.2.2"
NUC_BIN="nix-user-chroot-bin-1.2.2-x86_64-unknown-linux-musl"
NIX_DIR=$HOME/.nix


function install_nix { # https://nixos.wiki/wiki/Nix_Installation_Guide
	unshare --user --pid echo YES;
	grep CONFIG_USER_NS /boot/config-$(uname -r);
	mkdir -m 0755 $NIX_DIR
	cd $NIX_DIR

	# Getting nix-user-chroot binary
	wget $NUC_SRC/$NUC_BIN
	mv $NUC_BIN nix-user-chroot
	chmod +x ./nix-user-chroot

	# Install nix
	echo "INSTALLING NIX... THIS WILL TAKE A COUPLE MINUTES" && sleep 5;
	./nix-user-chroot $NIX_DIR $OYSTER -c 'curl -L https://nixos.org/nix/install | sh'

	# Install i3, fzf, ack, neovim, nodejs for cocnvim
	$NIX_DIR/nix-user-chroot $NIX_DIR $OYSTER -c "

		# /!\ Care for the dot "."
		. $HOME/.nix-profile/etc/profile.d/nix.sh;

		# Install packages
		nix-env -iA        \
			nixpkgs.i3     \
			nixpkgs.neovim \
			nixpkgs.fzf    \
			nixpkgs.nodejs \
			nixpkgs.ack    \
			nixpkgs.rofi   \
		    nixpkgs.fasd;
	"
}


function start_nix() { $NIX_DIR/nix-user-chroot $NIX_DIR $OYSTER -c $XEPHYR_START }


while [ True ]; do
	if   [ "$1" = "-i" -o "$1" = "--install" ]; then install_nix;  shift 1;
	elif [ "$1" = "-s" -o "$1" = "--start"   ]; then start_nix; shift 1;
	else break;
	fi
done

